/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ng2-keycloak.module';
import * as import2 from '@angular/http';
import * as import3 from './services/keycloak.core.service';
import * as import4 from './services/keycloak.auth.service';
import * as import5 from './services/keycloak.http.service';
class Ng2KeycloakModuleInjector extends import0.ɵNgModuleInjector<import1.Ng2KeycloakModule> {
  _HttpModule_0:import2.HttpModule;
  _Ng2KeycloakModule_1:import1.Ng2KeycloakModule;
  __BrowserXhr_2:import2.BrowserXhr;
  __ResponseOptions_3:import2.BaseResponseOptions;
  __XSRFStrategy_4:any;
  __XHRBackend_5:import2.XHRBackend;
  __RequestOptions_6:import2.BaseRequestOptions;
  __Keycloak_7:import3.Keycloak;
  __KeycloakAuthorization_8:import4.KeycloakAuthorization;
  __Http_9:any;
  __KeycloakHttp_10:import5.KeycloakHttp;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_2():import2.BrowserXhr {
    if ((this.__BrowserXhr_2 == null)) { (this.__BrowserXhr_2 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_2;
  }
  get _ResponseOptions_3():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_3 == null)) { (this.__ResponseOptions_3 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_3;
  }
  get _XSRFStrategy_4():any {
    if ((this.__XSRFStrategy_4 == null)) { (this.__XSRFStrategy_4 = import2.ɵb()); }
    return this.__XSRFStrategy_4;
  }
  get _XHRBackend_5():import2.XHRBackend {
    if ((this.__XHRBackend_5 == null)) { (this.__XHRBackend_5 = new import2.XHRBackend(this._BrowserXhr_2,this._ResponseOptions_3,this._XSRFStrategy_4)); }
    return this.__XHRBackend_5;
  }
  get _RequestOptions_6():import2.BaseRequestOptions {
    if ((this.__RequestOptions_6 == null)) { (this.__RequestOptions_6 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_6;
  }
  get _Keycloak_7():import3.Keycloak {
    if ((this.__Keycloak_7 == null)) { (this.__Keycloak_7 = new import3.Keycloak()); }
    return this.__Keycloak_7;
  }
  get _KeycloakAuthorization_8():import4.KeycloakAuthorization {
    if ((this.__KeycloakAuthorization_8 == null)) { (this.__KeycloakAuthorization_8 = new import4.KeycloakAuthorization(this._Keycloak_7)); }
    return this.__KeycloakAuthorization_8;
  }
  get _Http_9():any {
    if ((this.__Http_9 == null)) { (this.__Http_9 = import1.keycloakHttpFactory(this._XHRBackend_5,this._RequestOptions_6,this._Keycloak_7,this._KeycloakAuthorization_8)); }
    return this.__Http_9;
  }
  get _KeycloakHttp_10():import5.KeycloakHttp {
    if ((this.__KeycloakHttp_10 == null)) { (this.__KeycloakHttp_10 = new import5.KeycloakHttp(this.parent.get(import2.ConnectionBackend),this._RequestOptions_6,this._Keycloak_7,this._KeycloakAuthorization_8)); }
    return this.__KeycloakHttp_10;
  }
  createInternal():import1.Ng2KeycloakModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._Ng2KeycloakModule_1 = new import1.Ng2KeycloakModule();
    return this._Ng2KeycloakModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import1.Ng2KeycloakModule)) { return this._Ng2KeycloakModule_1; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_2; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_3; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_4; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_5; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_6; }
    if ((token === import3.Keycloak)) { return this._Keycloak_7; }
    if ((token === import4.KeycloakAuthorization)) { return this._KeycloakAuthorization_8; }
    if ((token === import2.Http)) { return this._Http_9; }
    if ((token === import5.KeycloakHttp)) { return this._KeycloakHttp_10; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2KeycloakModuleNgFactory:import0.NgModuleFactory<import1.Ng2KeycloakModule> = new import0.NgModuleFactory<any>(Ng2KeycloakModuleInjector,import1.Ng2KeycloakModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvZXN0ZXZhbi93b3Jrc3BhY2Uva2V5Y2xvYWstcXVpY2tzdGFydHMvYW5ndWxhcjQta2V5Y2xvYWsvc3JjL25nMi1rZXljbG9hay5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvZXN0ZXZhbi93b3Jrc3BhY2Uva2V5Y2xvYWstcXVpY2tzdGFydHMvYW5ndWxhcjQta2V5Y2xvYWsvc3JjL25nMi1rZXljbG9hay5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
